server:
  port: 8086
spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Jitendra369/micro-config-server
          clone-on-start: true
