server:
  port: 8082
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: microratingservice
  application:
    name: HOTEL-RATING

  config:
    import: optional:configserver:http://localhost:8086
#
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka

#okta configuration
okta:
  oauth2:
    issuer: https://dev-54593862.okta.com/oauth2/default
    audience: api://default