server:
  port: 8081
spring:
  application:
    name: HOTEL-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/microservicehotel
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

  config:
    import: optional:configserver:http://localhost:8086

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka


#okta configuration
okta:
  oauth2:
    issuer: https://dev-54593862.okta.com/oauth2/default
    audience: api://default